version: "3.8"
services:
  postgres-fastapi:
    image: postgres:14.1-alpine
    restart: always
    expose:
      - "${POSTGRES_EXPOSE}"
    ports:
      - "${POSTGRES_EXPOSE}:${POSTGRES_EXPOSE}"
    env_file:
      - ./.env
    volumes:
      - postgres-fastapi:/var/lib/postgresql/data/
    networks:
      - storage-service

  postgres-fastapi-test:
    image: postgres:14.1-alpine
    restart: always
    expose:
      - "${POSTGRES_EXPOSE_TEST}"
    ports:
      - "${POSTGRES_EXPOSE_TEST}:${POSTGRES_EXPOSE}"
    env_file:
      - ./.env
    networks:
      - storage-service

  backend:
    build: .
    command: sh -c "export PYTHONPATH=$(pwd) && cd ./src && alembic upgrade head && cd .. && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    ports:
      - ${DOCKER_APP_PORT:-8000}:8000
    volumes:
      - ./src/files:/files
    env_file:
      - ./.env
    restart: always
    depends_on:
      - postgres-fastapi
      - postgres-fastapi-test
    networks:
        - storage-service

volumes:
  postgres-fastapi:


networks:
  storage-service: