version: "3.3"
services:
  backend:
    build: .
    command: sh -c "${COMMANDS_BEFORE_START_BACK}"
    volumes:
      - images:/src/images/
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=file_storage_postgres
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    depends_on:
      - file_storage_postgres
    ports:
      - ${PROJECT_PORT}:${PROJECT_PORT}
    expose:
      - 9010

  postgres-fastapi:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${DB_PORT}:${DB_PORT}"
    expose:
      - "${DB_PORT}"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"


volumes:
    postgres_data:
    images:
