version: "3.8"
services:
  postgres-fastapi:
    image: postgres:14.1-alpine
    restart: always
    expose:
      - "${DB_PORT}"
    env_file:
      - ./.env

  backend:
    build: .
    command: sh -c "${COMMANDS_BEFORE_START_BACK}"
    ports:
      - ${PROJECT_PORT}:${PROJECT_PORT}
    volumes:
      - ./src/files:/code/src/files/
    env_file:
      - ./.env
    restart: always
    depends_on:
      - postgres-fastapi
