version: "3.8"
services:
  db:
    build:
        context: .
        dockerfile: ./dockerization/Dockerfile-db
    restart: always
    expose:
      - ${POSTGRES_EXPOSE}
    ports:
      - ${POSTGRES_EXPOSE}:${POSTGRES_PORT}
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_DB},${POSTGRES_DB_TEST}
    volumes:
      - db:/var/lib/postgresql/data/
    networks:
      - storage-service

  backend:
    build: .
    command: sh -c "export PYTHONPATH=$(pwd) && sleep 5 && cd ./src && alembic upgrade head && cd .. && python -m gunicorn --name file_service -k uvicorn.workers.UvicornWorker -w 1 -b 0.0.0.0:8000 src.main:app"
    ports:
      - ${DOCKER_APP_PORT:-8000}:8000
    volumes:
      - ./src/files:/files
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    networks:
        - storage-service

volumes:
  db:


networks:
  storage-service: